=== ellisaveta/FMI-XML/FinalProject/IT_products.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!--=====Simple Elements Declaration=====-->
	<xs:element name="Name" type="xs:ID" />
	<xs:element name="Model" type="xs:string" />
	<xs:element name="Price">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:fractionDigits fixed="true" value="2" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Weight" type="xs:decimal" />
	<xs:element name="MemorySize" type="xs:positiveInteger" />
	<xs:element name="HardDisk" type="xs:positiveInteger" />
	<xs:element name="NumUSBPorts" type="xs:positiveInteger" />
	<xs:element name="DiagonalSize">
		<xs:simpleType>
			<xs:restriction base="xs:decimal">
				<xs:fractionDigits fixed="true" value="1" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="AspectRatio">
		<xs:simpleType>
			<xs:restriction base="xs:token">
				<xs:pattern value="[1-9][0-9]*:[1-9][0-9]*" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="Buttons" type="xs:positiveInteger" />
	<xs:element name="MovementResolusion" type="xs:positiveInteger" />

	<!-- *************** Attributes ************** -->
	<xs:simpleType name="Region_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Asia" />
			<xs:enumeration value="America" />
			<xs:enumeration value="Europe" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="makerId_type">
		<xs:restriction base="xs:ID">
			<xs:pattern value="maker[1-9][0-9]*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="Category_type">
		<xs:restriction base="xs:string">
			<xs:enumeration value="laptop" />
			<xs:enumeration value="computer" />
			<xs:enumeration value="monitor" />
			<xs:enumeration value="mouse" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="productId_type">
		<xs:restriction base="xs:ID">
			<xs:pattern value="l[1-9][0-9]*|c[1-9][0-9]*|m[1-9][0-9]*|mo[1-9][0-9]*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="makerIdRef_type">
		<xs:restriction base="xs:IDREF">
			<xs:pattern value="maker[1-9][0-9]*" />
		</xs:restriction>
	</xs:simpleType>
	<!--=======Complex Elements=============-->
	<xs:element name="Maker">
		<xs:key name="makerKey">
			<xs:selector xpath="Catalog/Makers/Maker" />
			<xs:field xpath="Name" />
			<xs:field xpath="@makerId" />
		</xs:key>
	</xs:element>
	<xs:complexType name="Maker">
		<xs:sequence>
			<xs:element ref="Name" />
		</xs:sequence>
		<xs:attribute name="Region" type="Region_type" use="required" />
		<xs:attribute name="makerId" type="makerId_type" use="required" />
	</xs:complexType>
	<xs:element name="Product">
		<xs:keyref name="makerRef" refer="makerKey">
			<xs:selector xpath="Catalog/ITProducts/Product/Maker" />
			<xs:field xpath="@nameRef" />
			<xs:field xpath="@idRef" />
		</xs:keyref>
	</xs:element>
	<xs:complexType name="Product">
		<xs:sequence>
			<xs:element name="Maker" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="nameRef" type="xs:IDREF" use="required" />
					<xs:attribute name="idRef" type="makerIdRef_type" use="required" />
				</xs:complexType>
			</xs:element>
			<xs:element ref="Model" minOccurs="1" maxOccurs="1" />
			<xs:element ref="Price" minOccurs="1" maxOccurs="1" />
			<xs:element ref="Weight" minOccurs="0" maxOccurs="1" />
			<xs:element ref="MemorySize" minOccurs="0" maxOccurs="1" />
			<xs:element ref="HardDisk" minOccurs="0" maxOccurs="1" />
			<xs:element ref="NumUSBPorts" minOccurs="0" maxOccurs="1" />
			<xs:element ref="DiagonalSize" minOccurs="0" maxOccurs="1" />
			<xs:element ref="AspectRatio" minOccurs="0" maxOccurs="1" />
			<xs:element ref="Buttons" minOccurs="0" maxOccurs="1" />
			<xs:element ref="MovementResolusion" minOccurs="0" maxOccurs="1" />
			<xs:element name="image" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="href" type="xs:ENTITY" />
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="Category" type="Category_type" use="required" />
		<xs:attribute name="productId" type="productId_type" use="required" />
	</xs:complexType>
	<xs:element name="Makers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Maker" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ITProducts">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Product" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Catalog">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="Makers" />
				<xs:element ref="ITProducts" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ellisaveta/FMI-XML/FinalProject/IT_products.xml
<?xml version="1.0" encoding="UTF-8"?>

<?xml-stylesheet type="text/xsl" href="IT_products.xsl"?>
<!DOCTYPE Catalog [
	<!NOTATION jpg SYSTEM "image/jpg">
	<!ENTITY l1 SYSTEM "images/l1.jpg" NDATA jpg>
	<!ENTITY l2 SYSTEM "images/l2.jpg" NDATA jpg>
	<!ENTITY l3 SYSTEM "images/l3.jpg" NDATA jpg>
	<!ENTITY c1 SYSTEM "images/c1.jpg" NDATA jpg>
	<!ENTITY c2 SYSTEM "images/c2.jpg" NDATA jpg>
	<!ENTITY m1 SYSTEM "images/m1.jpg" NDATA jpg>
	<!ENTITY m2 SYSTEM "images/m2.jpg" NDATA jpg>
	<!ENTITY mo1 SYSTEM "images/mo1.jpg" NDATA jpg>
	<!--<!ATTLIST image href ENTITY #IMPLIED>-->
]>

<Catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="IT_products.xsd">
	<!--==========MAKERS=========-->
	<Makers>
		<Maker Region="Asia" makerId="maker1">
			<Name>Asus</Name>
		</Maker>
		<Maker Region="America" makerId="maker2">
			<Name>Dell</Name>
		</Maker>
		<Maker Region="Asia" makerId="maker3">
			<Name>Lenovo</Name>
		</Maker>
		<Maker Region="America" makerId="maker4">
			<Name>Apple</Name>
		</Maker>
		<Maker Region="Asia" makerId="maker5">
			<Name>Acer</Name>
		</Maker>
	</Makers>
	<!--=========PRODUCTS========-->
	<ITProducts>
		<Product Category="laptop" productId="l1">
			<Maker nameRef="Asus" idRef="maker1" />
			<Model>C223NA-GJ0055</Model>
			<Price>534.08</Price> <!--lv.-->
			<Weight>1</Weight> <!--kg-->
			<MemorySize>
			4</MemorySize> <!--GB-->
			<image href="l1" />
		</Product>
		<Product Category="laptop" productId="l2">
			<Maker nameRef="Dell" idRef="maker2" />
			<Model>Vostro 3510</Model>
			<Price>855.78</Price>
			<Weight>1.69</Weight>
			<MemorySize>
			8</MemorySize>
			<image href="l2" />
		</Product>
		<Product Category="laptop" productId="l3">
			<Maker nameRef="Apple" idRef="maker4" />
			<Model>MacBook Air 13.6</Model>
			<Price>2943.24</Price>
			<Weight>
			1.24</Weight>
			<MemorySize>8</MemorySize>
			<image href="l3" />
		</Product>

		<Product Category="computer" productId="c1">
			<Maker nameRef="Lenovo" idRef="maker3" />
			<Model>ThinkCentre Neo 50s</Model>
			<Price>1188.72</Price>
			<HardDisk>
			512</HardDisk>
			<NumUSBPorts>7</NumUSBPorts>
			<image href="c1" />
		</Product>
		<Product Category="computer" productId="c2">
			<Maker nameRef="Dell" idRef="maker2" />
			<Model>Vostro Desktop 3910</Model>
			<Price>1468.19</Price>
			<HardDisk>
			1000</HardDisk>
			<NumUSBPorts>8</NumUSBPorts>
			<image href="c2" />
		</Product>

		<Product Category="monitor" productId="m1">
			<Maker nameRef="Asus" idRef="maker1" />
			<Model>VZ24EHE</Model>
			<Price>269.64</Price>
			<DiagonalSize>
			23.8</DiagonalSize> <!--inch-->
			<AspectRatio>16:9</AspectRatio>
			<image href="m1" />
		</Product>
		<Product Category="monitor" productId="m2">
			<Maker nameRef="Lenovo" idRef="maker3" />
			<Model>ThinkVision S22e-20</Model>
			<Price>262.32</Price>
			<DiagonalSize>
			21.5</DiagonalSize>
			<AspectRatio>16:9</AspectRatio>
			<image href="m2" />
		</Product>

		<Product Category="mouse" productId="mo1">
			<Maker nameRef="Acer" idRef="maker5" />
			<Model>Centus 330</Model>
			<Price>99.36</Price>
			<Buttons>7</Buttons>
			<MovementResolusion>
			16000</MovementResolusion> <!--dpi-->
			<image href="mo1" />
		</Product>
	</ITProducts>
</Catalog>
